export const getData = /* async */ (/* url */) => {
	try {
		// const response = await fetch(url);
		const response = {
			count: 60,
			next: 'https://swapi.co/api/people/?search=a&page=2',
			results: [
				{
					birth_year: '19BBY',
					created: '2014-12-09T13:50:51.644000Z',
					edited: '2014-12-20T21:17:56.891000Z',
					eye_color: 'blue',
					films: [
						'https://swapi.co/api/films/2/',
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/3/',
						'https://swapi.co/api/films/1/',
						'https://swapi.co/api/films/7/',
					],
					gender: 'male',
					hair_color: 'blond',
					height: '172',
					homeworld: 'https://swapi.co/api/planets/1/',
					mass: '77',
					name: 'Luke Skywalker',
					skin_color: 'fair',
					species: ['https://swapi.co/api/species/1/'],
					starships: [
						'https://swapi.co/api/starships/12/',
						'https://swapi.co/api/starships/22/',
					],
					url: 'https://swapi.co/api/people/1/',
					vehicles: [
						'https://swapi.co/api/vehicles/14/',
						'https://swapi.co/api/vehicles/30/',
					],
				},
				{
					birth_year: '41.9BBY',
					created: '2014-12-10T15:18:20.704000Z',
					edited: '2014-12-20T21:17:50.313000Z',
					eye_color: 'yellow',
					films: [
						'https://swapi.co/api/films/2/',
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/3/',
						'https://swapi.co/api/films/1/',
					],
					gender: 'male',
					hair_color: 'none',
					height: '202',
					homeworld: 'https://swapi.co/api/planets/1/',
					mass: '136',
					name: 'Darth Vader',
					skin_color: 'white',
					species: ['https://swapi.co/api/species/1/'],
					starships: ['https://swapi.co/api/starships/13/'],
					url: 'https://swapi.co/api/people/4/',
					vehicles: [],
				},
				{
					birth_year: '19BBY',
					created: '2014-12-10T15:20:09.791000Z',
					edited: '2014-12-20T21:17:50.315000Z',
					eye_color: 'brown',
					films: [
						'https://swapi.co/api/films/2/',
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/3/',
						'https://swapi.co/api/films/1/',
						'https://swapi.co/api/films/7/',
					],
					gender: 'female',
					hair_color: 'brown',
					height: '150',
					homeworld: 'https://swapi.co/api/planets/2/',
					mass: '49',
					name: 'Leia Organa',
					skin_color: 'light',
					species: ['https://swapi.co/api/species/1/'],
					starships: [],
					url: 'https://swapi.co/api/people/5/',
					vehicles: ['https://swapi.co/api/vehicles/30/'],
				},
				{
					birth_year: '52BBY',
					created: '2014-12-10T15:52:14.024000Z',
					edited: '2014-12-20T21:17:50.317000Z',
					eye_color: 'blue',
					films: [
						'https://swapi.co/api/films/5/',
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/1/',
					],
					gender: 'male',
					hair_color: 'brown, grey',
					height: '178',
					homeworld: 'https://swapi.co/api/planets/1/',
					mass: '120',
					name: 'Owen Lars',
					skin_color: 'light',
					species: ['https://swapi.co/api/species/1/'],
					starships: [],
					url: 'https://swapi.co/api/people/6/',
					vehicles: [],
				},
				{
					birth_year: '47BBY',
					created: '2014-12-10T15:53:41.121000Z',
					edited: '2014-12-20T21:17:50.319000Z',
					eye_color: 'blue',
					films: [
						'https://swapi.co/api/films/5/',
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/1/',
					],
					gender: 'female',
					hair_color: 'brown',
					height: '165',
					homeworld: 'https://swapi.co/api/planets/1/',
					mass: '75',
					name: 'Beru Whitesun lars',
					skin_color: 'light',
					species: ['https://swapi.co/api/species/1/'],
					starships: [],
					url: 'https://swapi.co/api/people/7/',
					vehicles: [],
				},
				{
					birth_year: '24BBY',
					created: '2014-12-10T15:59:50.509000Z',
					edited: '2014-12-20T21:17:50.323000Z',
					eye_color: 'brown',
					films: ['https://swapi.co/api/films/1/'],
					gender: 'male',
					hair_color: 'black',
					height: '183',
					homeworld: 'https://swapi.co/api/planets/1/',
					mass: '84',
					name: 'Biggs Darklighter',
					skin_color: 'light',
					species: ['https://swapi.co/api/species/1/'],
					starships: ['https://swapi.co/api/starships/12/'],
					url: 'https://swapi.co/api/people/9/',
					vehicles: [],
				},
				{
					birth_year: '57BBY',
					created: '2014-12-10T16:16:29.192000Z',
					edited: '2014-12-20T21:17:50.325000Z',
					eye_color: 'blue-gray',
					films: [
						'https://swapi.co/api/films/2/',
						'https://swapi.co/api/films/5/',
						'https://swapi.co/api/films/4/',
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/3/',
						'https://swapi.co/api/films/1/',
					],
					gender: 'male',
					hair_color: 'auburn, white',
					height: '182',
					homeworld: 'https://swapi.co/api/planets/20/',
					mass: '77',
					name: 'Obi-Wan Kenobi',
					skin_color: 'fair',
					species: ['https://swapi.co/api/species/1/'],
					starships: [
						'https://swapi.co/api/starships/48/',
						'https://swapi.co/api/starships/59/',
						'https://swapi.co/api/starships/64/',
						'https://swapi.co/api/starships/65/',
						'https://swapi.co/api/starships/74/',
					],
					url: 'https://swapi.co/api/people/10/',
					vehicles: ['https://swapi.co/api/vehicles/38/'],
				},
				{
					birth_year: '41.9BBY',
					created: '2014-12-10T16:20:44.310000Z',
					edited: '2014-12-20T21:17:50.327000Z',
					eye_color: 'blue',
					films: [
						'https://swapi.co/api/films/5/',
						'https://swapi.co/api/films/4/',
						'https://swapi.co/api/films/6/',
					],
					gender: 'male',
					hair_color: 'blond',
					height: '188',
					homeworld: 'https://swapi.co/api/planets/1/',
					mass: '84',
					name: 'Anakin Skywalker',
					skin_color: 'fair',
					species: ['https://swapi.co/api/species/1/'],
					starships: [
						'https://swapi.co/api/starships/59/',
						'https://swapi.co/api/starships/65/',
						'https://swapi.co/api/starships/39/',
					],
					url: 'https://swapi.co/api/people/11/',
					vehicles: [
						'https://swapi.co/api/vehicles/44/',
						'https://swapi.co/api/vehicles/46/',
					],
				},
				{
					birth_year: '64BBY',
					created: '2014-12-10T16:26:56.138000Z',
					edited: '2014-12-20T21:17:50.330000Z',
					eye_color: 'blue',
					films: [
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/1/',
					],
					gender: 'male',
					hair_color: 'auburn, grey',
					height: '180',
					homeworld: 'https://swapi.co/api/planets/21/',
					mass: 'unknown',
					name: 'Wilhuff Tarkin',
					skin_color: 'fair',
					species: ['https://swapi.co/api/species/1/'],
					starships: [],
					url: 'https://swapi.co/api/people/12/',
					vehicles: [],
				},
				{
					birth_year: '200BBY',
					created: '2014-12-10T16:42:45.066000Z',
					edited: '2014-12-20T21:17:50.332000Z',
					eye_color: 'blue',
					films: [
						'https://swapi.co/api/films/2/',
						'https://swapi.co/api/films/6/',
						'https://swapi.co/api/films/3/',
						'https://swapi.co/api/films/1/',
						'https://swapi.co/api/films/7/',
					],
					gender: 'male',
					hair_color: 'brown',
					height: '228',
					homeworld: 'https://swapi.co/api/planets/14/',
					mass: '112',
					name: 'Chewbacca',
					skin_color: 'unknown',
					species: ['https://swapi.co/api/species/3/'],
					starships: [
						'https://swapi.co/api/starships/10/',
						'https://swapi.co/api/starships/22/',
					],
					url: 'https://swapi.co/api/people/13/',
					vehicles: ['https://swapi.co/api/vehicles/19/'],
				},
			],
		};
		// const data = await response.json();

		return response;
	} catch (error) {
		return new Error(error);
	}
};
